# Generated by Django 4.0.4 on 2022-05-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Rectangle', models.ImageField(default='temp.png', null=True, upload_to='')),
                ('Image_Circle', models.ImageField(default='temp.png', null=True, upload_to='')),
            ],
        ),
    ]
