# Generated by Django 4.0.4 on 2022-05-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_cake_topper'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeRequestPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_left', models.ImageField(default='temp.png', help_text="Please note these won't show on mobile", null=True, upload_to='')),
                ('Image_right', models.ImageField(default='temp.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TopperRequestPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_left', models.ImageField(default='temp.png', help_text="Please note these won't show on mobile", null=True, upload_to='')),
                ('Image_right', models.ImageField(default='temp.png', null=True, upload_to='')),
            ],
        ),
    ]
