# Generated by Django 4.0.4 on 2022-05-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_cakerequestphotos_topperrequestphotos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CakeRequestPhotos',
        ),
        migrations.DeleteModel(
            name='TopperRequestPhotos',
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name_plural': 'Cake Request Page - Customer Requests'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact Page - Customer Requests'},
        ),
        migrations.AlterModelOptions(
            name='contactphotos',
            options={'verbose_name_plural': 'Contact Page - Images'},
        ),
        migrations.AlterModelOptions(
            name='topper',
            options={'verbose_name_plural': 'Topper Request Page - Customer Requests'},
        ),
    ]
