# Generated by Django 4.0.4 on 2022-05-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeGalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='temp.png', help_text='Please add as many as you would like!', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CakeGalleryWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopperGalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='temp.png', help_text='Please add as many as you would like!', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TopperGalleryWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(max_length=400, null=True)),
            ],
        ),
    ]
