# Generated by Django 4.0.4 on 2022-05-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cakegalleryimages',
            options={'verbose_name_plural': 'Cake Gallery Page - Images'},
        ),
        migrations.AlterModelOptions(
            name='cakegallerywriting',
            options={'verbose_name_plural': 'Cake Gallery Page - Text'},
        ),
        migrations.AlterModelOptions(
            name='toppergalleryimages',
            options={'verbose_name_plural': 'Topper Gallery Page - Images'},
        ),
        migrations.AlterModelOptions(
            name='toppergallerywriting',
            options={'verbose_name_plural': 'Topper Gallery Page - Text'},
        ),
    ]
