# Generated by Django 4.0.4 on 2022-04-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Overall_website_description', models.CharField(max_length=400, null=True)),
                ('Cakes_Title', models.CharField(max_length=50, null=True)),
                ('Cakes_More_Info', models.CharField(max_length=300, null=True)),
                ('Toppers_Title', models.CharField(max_length=50, null=True)),
                ('Toppers_More_Info', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
