# Generated by Django 4.0.4 on 2022-04-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagewriting',
            name='Cakes_More_Info',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='homepagewriting',
            name='Overall_website_description',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='homepagewriting',
            name='Toppers_More_Info',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
