# Generated by Django 4.0.4 on 2022-05-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_homepagewriting_cakes_more_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagewriting',
            name='Cakes_More_Info',
            field=models.TextField(help_text='The text has to take up 7 lines (when viewing on computer) on the page for proper formatting', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagewriting',
            name='Toppers_More_Info',
            field=models.TextField(help_text='The text has to take up 7 lines (when viewing on computer) on the page for proper formatting', max_length=300, null=True),
        ),
    ]
