# Generated by Django 4.0.4 on 2022-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_homepagewriting_cakes_more_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagewriting',
            name='cakes_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
