# Generated by Django 4.0.4 on 2022-05-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_homepagewriting_cakes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagewriting',
            name='home_image_1',
            field=models.ImageField(default='temp.svg', help_text='Image 1/4 going underneath website description. Recommended to be cake/topper', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepagewriting',
            name='home_image_2',
            field=models.ImageField(default='temp.svg', help_text='Image 2/4 going underneath website description. Recommended to be cake/topper', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepagewriting',
            name='home_image_3',
            field=models.ImageField(default='temp.svg', help_text='Image 3/4 going underneath website description. Recommended to be cake/topper', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepagewriting',
            name='home_image_4',
            field=models.ImageField(default='temp.svg', help_text='Image 4/4 going underneath website description. Recommended to be cake/topper', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepagewriting',
            name='home_image_main',
            field=models.ImageField(default='temp.svg', help_text='Big circular image on home page. Should be one of your best images/ nice picture of you. Light background would be best', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepagewriting',
            name='toppers_image',
            field=models.ImageField(default='temp.svg', help_text='Image going with toppers popup. Recommended to be a topper', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepagewriting',
            name='cakes_image',
            field=models.ImageField(default='temp.svg', help_text='Image going with cakes popup. Recommended to be a cake', null=True, upload_to=''),
        ),
    ]
