# Generated by Django 4.0.4 on 2022-05-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_homepagewriting_home_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Title', models.CharField(max_length=50, null=True)),
                ('About_Description', models.TextField(max_length=400, null=True)),
                ('Point_1_Title', models.CharField(max_length=50, null=True)),
                ('Point_1_Description', models.TextField(max_length=400, null=True)),
                ('Point_1_Image', models.ImageField(default='temp.png', help_text='Will be cropped into a circle. Recommended to be relevant to your point', null=True, upload_to='')),
                ('Point_2_Title', models.CharField(max_length=50, null=True)),
                ('Point_2_Description', models.TextField(max_length=400, null=True)),
                ('Point_2_Image', models.ImageField(default='temp.png', help_text='Will be cropped into a circle. Recommended to be relevant to your point', null=True, upload_to='')),
                ('Point_3_Title', models.CharField(max_length=50, null=True)),
                ('Point_3_Description', models.TextField(max_length=400, null=True)),
                ('Point_3_Image', models.ImageField(default='temp.png', help_text='Will be cropped into a circle. Recommended to be relevant to your point. Let me know if you need less/more points overall', null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='homepagewriting',
            name='cakes_image',
            field=models.ImageField(default='temp.png', help_text='Image going with cakes popup. Recommended to be a cake', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepagewriting',
            name='home_image_1',
            field=models.ImageField(default='temp.png', help_text='Image 1/4 going underneath website description. Recommended to be cake/topper', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepagewriting',
            name='home_image_2',
            field=models.ImageField(default='temp.png', help_text='Image 2/4 going underneath website description. Recommended to be cake/topper', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepagewriting',
            name='home_image_3',
            field=models.ImageField(default='temp.png', help_text='Image 3/4 going underneath website description. Recommended to be cake/topper', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepagewriting',
            name='home_image_4',
            field=models.ImageField(default='temp.png', help_text='Image 4/4 going underneath website description. Recommended to be cake/topper', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepagewriting',
            name='home_image_main',
            field=models.ImageField(default='temp.png', help_text='Big circular image on home page. Should be one of your best images/ nice picture of you. Light background would be best', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepagewriting',
            name='toppers_image',
            field=models.ImageField(default='temp.png', help_text='Image going with toppers popup. Recommended to be a topper', null=True, upload_to=''),
        ),
    ]
