# Generated by Django 4.0.4 on 2022-05-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_aboutpagewriting_alter_homepagewriting_cakes_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakesWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(max_length=400, null=True)),
                ('Button', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToppersWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(max_length=400, null=True)),
                ('Button', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
