# Generated by Django 4.0.4 on 2022-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cakeswriting_topperswriting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakesPageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', models.ImageField(default='temp.png', null=True, upload_to='')),
                ('Image2', models.ImageField(default='temp.png', null=True, upload_to='')),
                ('Image3', models.ImageField(default='temp.png', null=True, upload_to='')),
            ],
        ),
    ]
