# Generated by Django 4.0.4 on 2022-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_cakespageimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakesPageInitialImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', models.ImageField(default='temp.png', null=True, upload_to='')),
                ('Image2', models.ImageField(default='temp.png', null=True, upload_to='')),
                ('Image3', models.ImageField(default='temp.png', null=True, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='CakesPageImages',
            new_name='CakesPageAdditionalImages',
        ),
        migrations.RenameField(
            model_name='cakespageadditionalimages',
            old_name='Image1',
            new_name='Image_centre',
        ),
        migrations.RenameField(
            model_name='cakespageadditionalimages',
            old_name='Image2',
            new_name='Image_left',
        ),
        migrations.RenameField(
            model_name='cakespageadditionalimages',
            old_name='Image3',
            new_name='Image_right',
        ),
    ]
