# Generated by Django 4.0.4 on 2022-05-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_cakespageinitialimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppersPageAdditionalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_left', models.ImageField(default='temp.png', null=True, upload_to='')),
                ('Image_centre', models.ImageField(default='temp.png', null=True, upload_to='')),
                ('Image_right', models.ImageField(default='temp.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ToppersPageInitialImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', models.ImageField(default='temp.png', null=True, upload_to='')),
                ('Image2', models.ImageField(default='temp.png', null=True, upload_to='')),
                ('Image3', models.ImageField(default='temp.png', null=True, upload_to='')),
            ],
        ),
    ]
