# Generated by Django 4.0.4 on 2022-05-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_currenttoppersforsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenttoppersforsale',
            name='Esty_Link',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
