# Generated by Django 4.0.4 on 2022-05-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_currenttoppersforsale_esty_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currenttoppersforsale',
            name='Esty_Link',
        ),
        migrations.AddField(
            model_name='currenttoppersforsale',
            name='Url',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
