# Generated by Django 4.0.4 on 2022-05-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_currenttoppersforsale_esty_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenttoppersforsale',
            name='Url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
