# Generated by Django 4.0.4 on 2022-05-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_currenttoppersforsale_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topperswriting',
            name='Current_Designs_Description',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='topperswriting',
            name='Current_Designs_Title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
