# Generated by Django 4.0.4 on 2022-05-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_topperswriting_current_designs_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagewriting',
            options={'verbose_name_plural': 'About Page - Text and Images Upper Half'},
        ),
        migrations.AlterModelOptions(
            name='cakespageadditionalimages',
            options={'verbose_name_plural': 'Cakes Page - Images Optional'},
        ),
        migrations.AlterModelOptions(
            name='cakespageinitialimages',
            options={'verbose_name_plural': 'Cakes Page - Images'},
        ),
        migrations.AlterModelOptions(
            name='cakeswriting',
            options={'verbose_name_plural': 'Cakes Page - Text'},
        ),
        migrations.AlterModelOptions(
            name='currenttoppersforsale',
            options={'verbose_name_plural': 'Toppers Page - Current Postings'},
        ),
        migrations.AlterModelOptions(
            name='homepagewriting',
            options={'verbose_name_plural': 'Home Page - Text and Images'},
        ),
        migrations.AlterModelOptions(
            name='topperspageadditionalimages',
            options={'verbose_name_plural': 'Toppers Page - Images Optional'},
        ),
        migrations.AlterModelOptions(
            name='topperspageinitialimages',
            options={'verbose_name_plural': 'Toppers Page - Images'},
        ),
        migrations.AlterModelOptions(
            name='topperswriting',
            options={'verbose_name_plural': 'Toppers Page - Text'},
        ),
        migrations.AddField(
            model_name='cakeswriting',
            name='background_image',
            field=models.ImageField(default='temp.png', help_text='For the bottom half of the screen only. May be a struggle to find one you can like that looks good on both computer and mobile. In that case  feel free to upload an image of all one colour.', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cakeswriting',
            name='bottom_half_heading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cakeswriting',
            name='bottom_half_small_image',
            field=models.ImageField(default='temp.png', help_text="Haven't tested it but I have a feeling an image may be too busy. Feel free to insert a white image or a clipart cake image provided it is under a creative commons usage(you can filter that on google) ", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cakeswriting',
            name='bottom_half_text',
            field=models.TextField(help_text='Please aim for 2-4 sentences', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='cakeswriting',
            name='Button',
            field=models.CharField(help_text='The upper button', max_length=50, null=True),
        ),
    ]
